services:
    db:
        image: postgres
        container_name: db_ci-cd
        restart: always #container reinicia se morrer
        ports:
            - 2345:5432
        env_file:
            - .env #configurar POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB
        volumes:
            - postgres:/var/lib/postgresql/data
    node_app:
        container_name: node_app_ci-cd
        build: . #Dockerfile do node se encontra na pasta atual
        ports:
            - 5000:5000
        depends_on:
            - db # sรณ sobe quando o postgres tiver no ar
        env_file:
            - .env #configurar DATABASE_URL

volumes:
    postgres:
