services:
    db:
        image: postgres
        container_name: db_ci-cd-test
        restart: always
        ports:
            - 2345:5432
        env_file:
            - .env.test

    node_app:
        container_name: node_app_ci-cd-test
        build: .
        ports:
            - 5000:5000
        env_file:
            - .env.test
        depends_on:
            - db
